# Generated by Django 3.2.7 on 2021-09-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='sport_turlar/')),
            ],
        ),
        migrations.CreateModel(
            name='SportCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('manzil', models.CharField(max_length=255)),
                ('telfon', models.CharField(max_length=25)),
                ('opens', models.TimeField()),
                ('closes', models.TimeField()),
                ('photo', models.ImageField(upload_to='sport_tu/')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longtitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('sport_turi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport_centers', to='main.sportturi')),
            ],
        ),
    ]
