# Generated by Django 3.2.7 on 2021-09-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportcenter',
            options={'ordering': ('nomi',)},
        ),
        migrations.AlterField(
            model_name='sportcenter',
            name='photo',
            field=models.ImageField(upload_to='sport_centers/'),
        ),
    ]
