# Generated by Django 3.2.6 on 2021-08-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportcenter',
            name='location',
        ),
        migrations.AddField(
            model_name='sportcenter',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1.9, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportcenter',
            name='longtitude',
            field=models.DecimalField(decimal_places=6, default=1.9, max_digits=9),
            preserve_default=False,
        ),
    ]
