# Generated by Django 3.2.7 on 2021-09-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210914_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportcenter',
            name='photo',
            field=models.ImageField(blank=True, upload_to='sport_centers/'),
        ),
        migrations.AlterField(
            model_name='sportturi',
            name='photo',
            field=models.ImageField(blank=True, upload_to='sport_turlar/'),
        ),
    ]
