# Generated by Django 3.2.6 on 2021-08-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210831_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportcenter',
            name='telfon',
            field=models.CharField(default='11', max_length=25),
            preserve_default=False,
        ),
    ]
